[package]
name = "blockchain"
version = "0.1.0"
authors = ["Nicolas Di Prima <nicolas.diprima@iohk.io>"]
edition = "2018"

[dependencies]
chain-impl-mockchain = { git = "https://github.com/input-output-hk/chain-libs.git", branch = "explicit-spending-counter" }
chain-time           = { git = "https://github.com/input-output-hk/chain-libs.git", branch = "explicit-spending-counter"}
thiserror = "1.0.21"
lru       = "0.6.1"
